### ISSUE TITLE
syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE)

### ISSUE THREAD

**Issue by Gaurav-Jadhav** [smaranchand/bucky#2]
**Describe the bug**
http://172.16.7.150:13337/manual_check.php
I entered "github.com"

URL get redirected to http://172.16.7.150:13337/process.php
response:
Blank page

logs:

[Thu Aug  6 23:19:52 2020] 172.16.7.13:61243 [500]: /process.php - syntax error, unexpected '' 
(T_ENCAPSED_AND_WHITESPACE), expecting identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in /root/gaurav/bucky/process.php on line 40

**Comment by smaranchand** [comment]
Hi @Gaurav-Jadhav , Seems like your device is configured to have Class- B Network and you are not running bucky backend engine on 127.0.0.1,  the Bucky backend engine runs at 127.0.0.1:13337  also the addon makes a POST request to  https://127.0.0.1:13337/process.php You can fix it by changing the listening IP and port at  ```./run.sh ``` file to ``` 172.16.7.150:13337 ``` as well as changing at ``` /addon/bucky.js  ``` on line 25.

**Comment by smaranchand** [comment]
Hi @Gaurav-Jadhav , Thanks for bringing this to attention, I researched  and discovered that it didn't happened because of the above problem I have described, It seems like your PHP version is not greater than or equal to 7.3 .
Please do upgrade your PHP version to use Bucky without problem.

Regards,
Smaran

**Comment by smaranchand** [comment]
I
