### ISSUE TITLE
Bucky not working with Firefox 68.11.0

### ISSUE THREAD

**Issue by corrupted-brain** [smaranchand/bucky#7]
**Describe the bug**
Bucky is unable to get bucket names from visited sites to the server. However, manual check is working perfectly.

**Desktop (please complete the following information):**
 - OS:Kali Linux
 - Browser: Firefox
 - Version: 68.11.0

**Comment by smaranchand** [comment]
Hi @corrupted-brain  , Thankyou for bringing attention to this, I personally checked the issue and was able to reproduce it. Based on the provided information, it seems a user can manually check for Bucket misconfiguration via Bucky dashboard(Manual Check)  but is unable by visiting web pages, which means the Bucky addon is not sending data to the backend engine.

This is the first strange issue received so far, and indeed its a valid one, I would be glad enough if you could provide the installed PHP version ```php -v``` and output of  ```./run.sh``` . I am working on it to find the root cause and  will let you know about the updates soon.

Regards,
Smaran

**Comment by corrupted-brain** [comment]
I updated entire OS and now its working.
Used PHP version is: PHP 7.4.9

**Comment by smaranchand** [comment]
Hi @corrupted-brain , Glad to hear that, Thanks for trying out Bucky.

Regards,
Smaran
